In [1]:
print("Hi")

Hi

In [1]:
import pandas as pd
product_data = pd.read_csv(r'E:\Customer_Support_System\data\flipkart_product_review.csv')

In [2]:
product_data.head()

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...

In [3]:
product_data.shape

(450, 5)

In [6]:
product_data.columns

Index(['product_id', 'product_title', 'rating', 'summary', 'review'], dtype='str')

In [7]:
product_list = []
for index, row in product_data.iterrows():
    object = {
        "product_name":row['product_title'],
        "product_rating":row['rating'],
        "product_summary":row['summary'],
        "product_review":row['review']
    }
    product_list.append(object)

In [9]:
product_list[1]

{'product_name': 'BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset',
 'product_rating': 5,
 'product_summary': 'Terrific purchase',
 'product_review': 'Super sound and good looking I like that prize'}

In [12]:
product_list[0]

{'product_name': 'BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset',
 'product_rating': 5,
 'product_summary': 'Terrific purchase',
 'product_review': "1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric..."}

In [1]:
from google.generativeai import list_models
print("models availibility:--->", [m.name for m in list_models()])

e:\Customer_Support_System\rag_env1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Kishore kumar V\AppData\Local\Temp\ipykernel_321516\2421296546.py:1: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  from google.generativeai import list_models

models availibility:---> ['models/gemini-2.5-flash', 'models/gemini-2.5-pro', 'models/gemini-2.0-flash', 'models/gemini-2.0-flash-001', 'models/gemini-2.0-flash-lite-001', 'models/gemini-2.0-flash-lite', 'models/gemini-2.5-flash-preview-tts', 'models/gemini-2.5-pro-preview-tts', 'models/gemma-3-1b-it', 'models/gemma-3-4b-it', 'models/gemma-3-12b-it', 'models/gemma-3-27b-it', 'models/gemma-3n-e4b-it', 'models/gemma-3n-e2b-it', 'models/gemma-4-26b-a4b-it', 'models/gemma-4-31b-it', 'models/gemini-flash-latest', 'models/gemini-flash-lite-latest', 'models/gemini-pro-latest', 'models/gemini-2.5-flash-lite', 'models/gemini-2.5-flash-image', 'models/gemini-3-pro-preview', 'models/gemini-3-flash-preview', 'models/gemini-3.1-pro-preview', 'models/gemini-3.1-pro-preview-customtools', 'models/gemini-3.1-flash-lite-preview', 'models/gemini-3-pro-image-preview', 'models/nano-banana-pro-preview', 'models/gemini-3.1-flash-image-preview', 'models/lyria-3-clip-preview', 'models/lyria-3-pro-preview', 'models/gemini-robotics-er-1.5-preview', 'models/gemini-2.5-computer-use-preview-10-2025', 'models/deep-research-pro-preview-12-2025', 'models/gemini-embedding-001', 'models/gemini-embedding-2-preview', 'models/aqa', 'models/imagen-4.0-generate-001', 'models/imagen-4.0-ultra-generate-001', 'models/imagen-4.0-fast-generate-001', 'models/veo-2.0-generate-001', 'models/veo-3.0-generate-001', 'models/veo-3.0-fast-generate-001', 'models/veo-3.1-generate-preview', 'models/veo-3.1-fast-generate-preview', 'models/veo-3.1-lite-generate-preview', 'models/gemini-2.5-flash-native-audio-latest', 'models/gemini-2.5-flash-native-audio-preview-09-2025', 'models/gemini-2.5-flash-native-audio-preview-12-2025', 'models/gemini-3.1-flash-live-preview']

In [5]:
# import os
# from dotenv import load_dotenv
# load_dotenv()

# required_variables = ['GROQ_API_KEY',"HF_TOKEN","kishore"]
# missing_vars=[ var for var in required_variables if not os.getenv(var)]
# if missing_vars:
#     raise EnvironmentError(f"Missing environment variables: {missing_vars}")

In [7]:
import pandas as pd

data = pd.read_csv(r'E:\Customer_Support_System\data\flipkart_product_review.csv')
data.head()

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...

In [12]:
from langchain_core.documents import Document
documents = []

for index,row in data.iterrows():
    metadata={
        "product_name":row['product_title'],
        "product_rating":row['rating'],
        "product_summary":row['summary']
    }
    doc = Document(page_content=row["review"], metadata=metadata)
    documents.append(doc)

In [9]:
documents[0]

Document(metadata={'product_name': 'BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset', 'product_rating': 5, 'product_summary': 'Terrific purchase'}, page_content="1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric...")

In [13]:
product_list = []

for _, row in data.iterrows():
    product_entry = {
        "product_name": row['product_title'],
        "product_rating": row['rating'],
        "product_summary": row['summary'],
        "product_review": row['review']
    }
    product_list.append(product_entry)

    documents1 = []
    for entry in product_list:
        metadata = {
            "product_name": entry["product_name"],
            "product_rating": entry["product_rating"],
            "product_summary": entry["product_summary"]
        }
        doc = Document(page_content=entry["product_review"], metadata=metadata)
        documents1.append(doc)

In [21]:
documents[0]

Document(metadata={'product_name': 'BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset', 'product_rating': 5, 'product_summary': 'Terrific purchase'}, page_content="1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric...")

In [25]:
documents1[0].metadata['product_name']

'BoAt Rockerz 235v2 with ASAP charging Version 5.0 Bluetooth Headset'

In [27]:
from config import config_loaders
config_loaders()

ModuleNotFoundError: No module named 'config'

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

Base =os.getenv('PROJECT_DATA_DIR')
print(Base)

E:\custmor_support_project_genai\data\flipkart_product_review.csv

In [3]:
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
print(BASE_DIR)

NameError: name '__file__' is not defined

In [8]:
a = True

if a:
    print("Value is there",a)

Value is there True